
server:
  port: 7777
  servlet:
    context-path: /uaa
spring:
  application:
    name: auth-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}